version: '3.4'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    env_file:
      - ./configs/db.env
    volumes:
     - db_data:/var/lib/mysql
    ports: 
    - "3306:3306"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - configs/web.env
    ports:
      - "8080:8080"


volumes:
  db_data:

